// chayan-1906
export default {
    "login": "chayan-1906",
    "id": 82430454,
    "node_id": "MDQ6VXNlcjgyNDMwNDU0",
    "avatar_url": "https://avatars.githubusercontent.com/u/82430454?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/chayan-1906",
    "html_url": "https://github.com/chayan-1906",
    "followers_url": "https://api.github.com/users/chayan-1906/followers",
    "following_url": "https://api.github.com/users/chayan-1906/following{/other_user}",
    "gists_url": "https://api.github.com/users/chayan-1906/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/chayan-1906/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/chayan-1906/subscriptions",
    "organizations_url": "https://api.github.com/users/chayan-1906/orgs",
    "repos_url": "https://api.github.com/users/chayan-1906/repos",
    "events_url": "https://api.github.com/users/chayan-1906/events{/privacy}",
    "received_events_url": "https://api.github.com/users/chayan-1906/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Padmanabha Das",
    "company": "Remix Labs",
    "blog": "",
    "location": "California",
    "email": null,
    "hireable": null,
    "bio": "Android & Flutter Developer",
    "twitter_username": null,
    "public_repos": 93,
    "public_gists": 0,
    "followers": 2,
    "following": 0,
    "created_at": "2021-04-13T04:15:00Z",
    "updated_at": "2023-07-09T17:49:05Z",
}

// pdas9647
/*
export default {
    "login": "pdas9647",
    "id": 74731500,
    "node_id": "MDQ6VXNlcjc0NzMxNTAw",
    "avatar_url": "https://avatars.githubusercontent.com/u/74731500?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/pdas9647",
    "html_url": "https://github.com/pdas9647",
    "followers_url": "https://api.github.com/users/pdas9647/followers",
    "following_url": "https://api.github.com/users/pdas9647/following{/other_user}",
    "gists_url": "https://api.github.com/users/pdas9647/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/pdas9647/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/pdas9647/subscriptions",
    "organizations_url": "https://api.github.com/users/pdas9647/orgs",
    "repos_url": "https://api.github.com/users/pdas9647/repos",
    "events_url": "https://api.github.com/users/pdas9647/events{/privacy}",
    "received_events_url": "https://api.github.com/users/pdas9647/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Padmanabha Das",
    "company": "Remix Labs",
    "blog": "",
    "location": "California",
    "email": null,
    "hireable": null,
    "bio": "Android and Flutter Developer",
    "twitter_username": null,
    "public_repos": 15,
    "public_gists": 0,
    "followers": 1,
    "following": 4,
    "created_at": "2020-11-19T17:27:15Z",
    "updated_at": "2023-06-30T04:33:53Z"
}*/
